# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('manet-dtn-example', ['manet-dtn','internet','wifi','applications','netanim'])
    obj.source = 'manet_dtn-test.cc'

