# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('manet-dtn', ['internet'])
    module.source = [
        'model/manet_dtn-routing-protocol.cc',
        'model/manet_dtn-state.cc',
        'model/manet_dtn-packet-queue.cc',
        'model/manet_dtn-header.cc',
        'model/manet_dtn-packet.cc',
        'model/manet_dtn-tag.cc',
        'helper/manet_dtn-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('manet-dtn')
    module_test.source = [
        'test/manet-dtn-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'manet-dtn'
    headers.source = [
        'model/manet_dtn-routing-protocol.h',
        'model/manet_dtn-header.h',
        'model/manet_dtn-state.h',
        'model/manet_dtn-packet-queue.h',
        'model/manet_dtn-repositories.h',
        'model/manet_dtn-packet.h',
        'model/manet_dtn-tag.h',
        'helper/manet_dtn-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

